services:
  app: &django-service
    image: smart-parking-lot
    build:
      context: .
      dockerfile: Containerfile
    environment:
      DJANGO_SQLITE_PATH: /app/data/db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:Z
  test:
    <<: *django-service
    profiles: [tools]
    ports: []
    command: ["uv", "run", "python", "manage.py", "test"]

  migrate:
    <<: *django-service
    profiles: [tools]
    ports: []
    command: ["uv", "run", "python", "manage.py", "migrate"]
